# Generated by Django 4.2.4 on 2024-08-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_alter_cartorder_options_cartorder_billingaddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="gst_rates_final",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=99999
            ),
        ),
    ]
