# Generated by Django 4.2.4 on 2024-08-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_alter_cartorderitems_gst_rates_final"),
    ]

    operations = [
        migrations.RemoveField(model_name="productreview", name="product",),
        migrations.RemoveField(model_name="productreview", name="user",),
        migrations.RemoveField(model_name="wishlist", name="product",),
        migrations.RemoveField(model_name="wishlist", name="user",),
        migrations.DeleteModel(name="Address",),
        migrations.DeleteModel(name="ProductReview",),
        migrations.DeleteModel(name="Wishlist",),
    ]
