# Generated by Django 4.2.4 on 2024-08-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_remove_product_deal_of_week_remove_product_featured"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="status",),
        migrations.RemoveField(model_name="productvarient", name="have_variation",),
        migrations.RemoveField(model_name="productvarient", name="in_stock",),
    ]
