# Generated by Django 4.2.4 on 2024-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_remove_product_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvarianttypes",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
